src/carts/urls.py
from django.urls import path, include

from .views import (
				cart_home,
				cart_add,
				checkout_home,
				checkout_done_view,
				# cart_remove,
				OrderDetail,
				OrderDelete,
				pay,
				)
app_name= "carts"
urlpatterns = [
	path('', cart_home, name="home"),
	path('update', cart_add, name="update"),
	# path('remove', cart_remove, name="remove"),
	path('checkout', checkout_home, name="checkout"),
	path('checkout/done', checkout_done_view, name="checkout_done"),
	path('order/<pk>', OrderDetail.as_view(), name="OrderDetail"),
	path('order/<int:pk>/delete', OrderDelete.as_view(), name="OrderDelete"),
	# path('paypal/', include('paypal.standard.ipn.urls')),
	path('pay/',pay,name='pay'),
	# path('guest_register', guest_register_view, name="guest_register"),
	# path('delete/<id>', removeproduct, name="remove"),
	]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from .views import home_page, about_page, contact_page
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page#, guest_register_view
from addresses.views import checkout_address_create_view
urlpatterns = [
	path('', home_page, name="home"),
	path('about/', about_page, name="about"),
	path('contact/', contact_page, name="contact"),
	#path(r'contact/view', contact_page),
	path('checkout/address/create', checkout_address_create_view, name="ckeckout_address_create"),
	path('login', login_page, name="login"),
	# path('register_guest', guest_register_view, name="guest_register"),
	path('logout/', LogoutView.as_view(), name="logout"),
	path('register', register_page , name="register"),
	path('bootstrap',TemplateView.as_view(template_name="bootstrap/example.html")),
	path('products/', include("products.urls")),
	path('search/', include("search.urls")),
	path('cart/', include("carts.urls")),
	# path('cart/', cart_home, name="cart"),
	path('admin/', admin.site.urls),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
    ]
if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path,include

from products.views import (
				ProductListView,
				ProductDetailslugView,
				ProductMenView,
				ProductWomenView
				)
app_name= "products"
urlpatterns = [
	path('', ProductListView.as_view(), name="list"),
	path('<slug>', ProductDetailslugView.as_view(), name="detail"),
	path('men/',ProductMenView.as_view(),name='men'),
	path('women/',ProductWomenView.as_view(),name='women')
	#url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
	

	#url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
	#url(r'^featured/$', ProductFeaturedListView.as_view()),
	#url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

	
	#url(r'^products-fbv/$', product_list_view),
	
]

src/templates/base/css.html
 {% load static %}
 <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">

src/templates/base/js.html
{% load static%}

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
	
</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous">
	
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous">
	
</script>
<script src="https://code.jquery.com/jquery-3.4.0.min.js" 
        integrity="sha384-JUMjoW8OzDJw4oFpWIB2Bu/c6768ObEthBMVSiIx4ruBIEdyNSUQAjJNFqT5pnJ6" 
        crossorigin="anonymous">
</script>
<script src="zoomsl.min.js"></script>
<script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>

src/templates/base/navbar.html
{% url "home" as home_url %}
{% url "contact" as contact_url %}
{% url "products:list"  as products_url %}
{% url "login" as login_url %}
{% url "logout" as logout_url %}
{% url "register" as register_url %}
{% url "carts:home" as cart_url %}
{% url "carts:checkout_done" as checkout_url %}
<!-- <h1>{{ brand_name }} </h1> -->
{% load static%}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3 ">

   
  <a class="navbar-brand" href="{{home_url}}">
      <a class="navbar-brand" href="{{home_url}}">
      <img src="{% static 'img/shop.png'%}" alt="">
    {% if brand_name%} 
        {{ brand_name}}
      {% else%}
Black Fashion
{% endif %}
</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item {% if request.path == home_url %} active {%endif%} ">
        <a class="nav-link" href="{{ home_url}}"><i class="fas fa-home"></i>Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item {% if request.path == contact_url %} active {%endif%}">
        <a class="nav-link" href="{{ contact_url }}"><i class="fas fa-address-book"></i>Contact</a>
      </li>
     
      <li class="nav-item {% if request.path == products_url %} active {%endif%}">
        <a class="nav-link " href="{{ products_url }}" tabindex="-1" ><img src="https://img.icons8.com/material/24/000000/tie.png">Products</a>
      </li>
       <li class="nav-item {% if request.path == cart_url %} active {%endif%}">
        <a class="nav-link " href="{{ cart_url }}" tabindex="-1" >{{request.session.cart_items}}&nbsp;<i class="fas fa-shopping-cart">Cart</i></a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item {% if request.path == logout_url %} active {%endif%}">
        <a class="nav-link " href="{{ logout_url }}?next={{request.GET.next}}" tabindex="-1" >Logout</a>
      </li>
       <li class="nav-item {% if request.path == checkout_url %} active {%endif%}">
        <a class="nav-link " href="{{ checkout_url }}?next={{request.GET.next}}" tabindex="-1" >My Orders</a>
      </li>
      {% else %}
       <li class="nav-item {% if request.path == login_url %} active {%endif%}">
        <a class="nav-link " href="{{ login_url }}" tabindex="-1" ><i class="fas fa-sign-in-alt">Login</i></a>
      </li>
      
       <li class="nav-item {% if request.path == register_url %} active {%endif%}">
        <a class="nav-link " href="{{ register_url }}" tabindex="-1" ><i class="fas fa-user-plus"></i>Register</a>
      </li>{% endif %}
      <!--  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#">Action</a>
      <a class="dropdown-item" href="#">Another action</a>
      <a class="dropdown-item" href="#">Something else here</a>
      <div class="dropdown-divider"></div>
      <a class="dropdown-item" href="#">Separated link</a>
    </div>
  </li> -->
    </ul>
  {% include 'search/snippets/search-form.html' %}
  </div>
</nav>
</div>