src/carts/urls.py
from django.urls import path, include

from .views import (
				cart_home,
				cart_add,
				checkout_home,
				checkout_done_view,
				# cart_remove,
				OrderDetail,
				OrderDelete,
				pay,
				)
app_name= "carts"
urlpatterns = [
	path('', cart_home, name="home"),
	path('update', cart_add, name="update"),
	# path('remove', cart_remove, name="remove"),
	path('checkout', checkout_home, name="checkout"),
	path('checkout/done', checkout_done_view, name="checkout_done"),
	path('order/<pk>', OrderDetail.as_view(), name="OrderDetail"),
	path('order/<int:pk>/delete', OrderDelete.as_view(), name="OrderDelete"),
	# path('paypal/', include('paypal.standard.ipn.urls')),
	path('pay/',pay,name='pay'),
	# path('guest_register', guest_register_view, name="guest_register"),
	# path('delete/<id>', removeproduct, name="remove"),
	]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from .views import home_page, about_page, contact_page
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page#, guest_register_view
from addresses.views import checkout_address_create_view
urlpatterns = [
	path('', home_page, name="home"),
	path('about/', about_page, name="about"),
	path('contact/', contact_page, name="contact"),
	#path(r'contact/view', contact_page),
	path('checkout/address/create', checkout_address_create_view, name="ckeckout_address_create"),
	path('login', login_page, name="login"),
	# path('register_guest', guest_register_view, name="guest_register"),
	path('logout/', LogoutView.as_view(), name="logout"),
	path('register', register_page , name="register"),
	path('bootstrap',TemplateView.as_view(template_name="bootstrap/example.html")),
	path('products/', include("products.urls")),
	path('search/', include("search.urls")),
	path('cart/', include("carts.urls")),
	# path('cart/', cart_home, name="cart"),
	path('admin/', admin.site.urls),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
    ]
if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/carts/models.py
from decimal import Decimal
from django.db import models
from django.conf import settings
from products.models import Product
from django.db.models.signals import pre_save, post_save, m2m_changed
from decimal import Decimal
# from payments import PurchasedItem
# from payments.models import BasePayment

User = settings.AUTH_USER_MODEL
class CartManager(models.Manager):
	def new_or_get(self, request):
		cart_id = request.session.get("cart_id", None)
		qs = self.get_queryset().filter(id=cart_id)
		if qs.count() == 1:
		    new_obj = False
		    cart_obj = qs.first()
		    if request.user.is_authenticated and cart_obj.user is None:
		        cart_obj.user = request.user
		        cart_obj.save()

		else:
		    cart_obj = Cart.objects.new(user=request.user)
		    new_obj = True
		    request.session['cart_id'] = cart_obj.id
		return cart_obj, new_obj

	def new(self, user=None):
	    user_obj = None
	    if user is not None:
	        if user.is_authenticated:
	            user_obj = user
	    return self.model.objects.create(user=user_obj)
class Cart(models.Model):
	
	user        = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
	products    = models.ManyToManyField(Product, blank=True)
	product_quantity=models.IntegerField(default=1)
	total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
	updated     = models.DateTimeField(auto_now=True)
	timestamp   = models.DateTimeField(auto_now_add=True)
	active      = models.BooleanField(default=False)
	objects = CartManager()

	def __str__(self):
		return str(self.id)

def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        products = instance.products.all()
        total = 0
        for x in products:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.products.through)
def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08) # 8% tax
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)
# class Payment(BasePayment):
# 	def get_failure_url(self):
# 		return 'payments/failure/'
# 	def get_success_url(self):
# 		return 'payments/success/'
# 	def get_purchased_items(self):
# 	# you'll probably want to retrieve these from an associated order
# 		yield PurchasedItem(name='The Hound of the Baskervilles', sku='BSKV',
# 		quantity=9, price=Decimal(10), currency='USD')
		

src/carts/views.py
from django.shortcuts import render, redirect, reverse
from django.urls import reverse_lazy
from .models import Cart
from billing.models import BillingProfile
from products.models import Product
from django.shortcuts import get_object_or_404
from orders.models import Order
from accounts.forms import LoginForm,RegisterForm
from addresses.models import Address
from addresses.forms import AddressForm
from django.http import JsonResponse
from django.views.generic import ListView,DetailView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404, redirect
from django.template.response import TemplateResponse
# from payments import get_payment_model, RedirectNeeded
# from paypal.standard.forms import PayPalPaymentsForm
from django.views.decorators.csrf import csrf_exempt


def cart_home(request):
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	return render(request, "carts/home.html", {"cart":cart_obj})

def cart_add(request):
	product_id = request.POST.get('product_id')

	if product_id is not None:
		try:
			product_obj = Product.objects.get(id=product_id)
		except Product.DoesNotExist:
			print(" product Out Of Stock")
			return redirect("carts:home")
	cart_obj, new_obj = Cart.objects.new_or_get(request)
	if product_obj in cart_obj.products.all():
		cart_obj.products.remove(product_obj)
		added = False
	else:
		cart_obj.products.add(product_obj) # cart_obj.products.add(product_id)
		added = True
		request.session['cart_items'] = cart_obj.products.count()

	return redirect("carts:home")
# def cart_remove(request):
# 	product_id=request.POST.get('product_id')
# 	if product_id is not None:
# 		try:
# 			product_obj = Product.objects.get(id=product_id)
# 		except Product.DoesNotExist:
# 			print("Product Not Found")
# 			return redirect("cart:home")
# 		cart_obj, new_obj = Cart.objects.get_or_create(request)
# 		if product_obj in cart_obj.products.all():
# 			cart_obj.products.remove(product_obj)
# 			added=False
# 		request.session['cart_items'] = cart_obj.products.count()
# 	return redirect("carts:home")
def checkout_home(request):
	cart_obj, cart_created = Cart.objects.new_or_get(request)
	order_obj = None
	if cart_created or cart_obj.products.count() == 0:
		return redirect("carts:home")
	login_form   = LoginForm()
	address_form = AddressForm()
	billing_address_id = request.session.get("billing_address_id", None)
	shipping_address_id = request.session.get("shipping_address_id", None)
	billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
	address_qs = None
	if billing_profile is not None:
		if request.user.is_authenticated:
			address_qs = Address.objects.filter(billing_profile=billing_profile)
		order_obj, order_obj_created = Order.objects.new_or_get(cart_obj=cart_obj,user=request.user)
		if shipping_address_id:
			order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
			del request.session["shipping_address_id"]
		if billing_address_id:
			order_obj.billing_address = Address.objects.get(id=billing_address_id)
			del request.session["billing_address_id"]
		if billing_address_id or shipping_address_id:
			order_obj.save(force_insert=False, force_update=False, using=None)
			# request.session.cart_items.delete()
			order_obj.save()
	context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "address_form": address_form,
        "address_qs": address_qs,
        }

	return render(request, "carts/checkout.html", context)

def checkout_done_view(request):
	orders=Order.objects.filter(user=request.user)
	return render(request, "carts/checkout-done.html", {'orders':orders})

class OrderDetail(DetailView):
	model = Order
	template_name="carts/order_detail.html"


class OrderDelete(UserPassesTestMixin,DeleteView):
	model = Order
	success_url = '/'
	def test_func(self):
		order= self.get_object()
		if self.request.user == order.user:
			return True
		return False

def pay(request):
	return render(request, 'carts/pay.html')

src/carts/templates/carts/checkout-done.html
{% extends "base.html" %}
{% block content %}
	<h1 class='mx-auto'>Your Orders:</h1>

<b>Please Note once Order Has been Shipped You couldn't Edit or delete it</b>
	{% for object in orders %}
	
	 <div class="card-columns">
	
	 <div class="card" style="width: 18rem;"> <div class="card-header">
    {{ object.status }}
  </div>
	  <div class="card-body">
	    <h5 class="card-title">Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</h5>
	    <h6 class="card-subtitle mb-2 text-muted">Shipping Address: {{ object.shipping_address.get_address }}</h6>
	    <p class="card-text">Cart Total: {{ object.cart.total }}</p>
	    <p class="card-text">Shipping Total: {{ object.shipping_total }}</p>
	    <p class="card-text">Order Total: {{ object.total }}</p>
	    <!-- <p class="card-text">Order Status: {{ object.status }}</p> -->
	    <a class='btn btn-success'href="{% url 'carts:OrderDetail' object.id %}" class="card-link">View</a>
	    <a class='btn btn-danger' href="{% url 'carts:OrderDelete' object.id %}" class="card-link">Delete</a>
	  </div>
	 </div>
    {% endfor %}
	</div>
	{%if not orders%}
	<div class="container"><h1 class="mx-auto">You haven't Any Orders</h1></div>{%endif%}
{% endblock %}

src/carts/templates/carts/checkout.html
 {% extends "base.html" %}


{% block content %}
{% if not billing_profile %}
    <div class='row text-center'>
    <div class='col-12 col-md-6'>
        <p class='lead'>Login</p>
        {% include 'accounts/snippets/form.html' with form=login_form next_url=request.build_absolute_uri %}
    </div>
    

    </div>

{% else %}
            
        {% if not object.shipping_address %}

         <div class='row'>
            <div class='col-12'>
                <p class='lead'>Shipping Address</p>
                <hr/>
            </div>
            <div class='col-6'>
                

           

                    {% url "checkout_address_create" as checkout_address_create %}
                    {% include 'addresses/form.html' with form=address_form  action_url=checkout_address_create next_url=request.build_absolute_uri %}



             </div>
        
        </div>


      
        </div>
        
            {% else %}
                <h1>Finalize Checkout</h1>
                <p>Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
                <p>Shipping Address: {{ object.shipping_address_final }}</p>
                
                <p>Cart Total: {{ object.cart.total }}</p>
                <p>Shipping Total: {{ object.shipping_total }}</p>
                <p>Order Total: {{ object.total }}</p>

                <form class='form' method='POST' action="{% url 'carts:checkout_done'%}">{% csrf_token %}
                    <button type='submit' class='btn btn-success'>Checkout</button>
                </form>
            {% endif %}
       

{% endif %}

{% endblock %}

src/carts/templates/carts/home.html
{% extends "base.html" %}



{% block content%}
<h1><i class="fas fa-shopping-cart">Cart</i></h1>
{% if cart.products.exists %}
	
			<table class="table">
		  <thead>
		    <tr>
		      <th scope="col">#</th>
		      <th scope="col">Product Name</th>
		      <th scope="col">Product Price</th>
		   
		    </tr>
		  </thead>
		  <tbody>
		  	{% for product in cart.products.all %}

		    <tr>
		      <th scope="row">{{forloop.counter}}</th>
		      <td><img src= "{{product.image.url}}"/ alt="" border=1 height=100 width=100></img><a href="{{product.get_absolute_url}}">{{product.title}}</a> {% include "products/update_cart.html" %}</td>
		      <td>{{product.price}}</td>
		     
		    </tr>
		    {% endfor %}
		    <tr>
		      <th colspan="2"></th>
		     
		      <th><b>Total:</b>{{cart.total}}</th>
		    </tr>
		      <tr>
		      <th colspan="2"><th><a class="btn btn-block btn-success" href="{% url 'carts:pay' %}" ><b>pay online</b></a></th>
		     
		      <th><a class="btn btn-block btn-success" href="{% url 'carts:checkout' %}" ><b>checkout</b></a></th>
		    </tr>
		 
		  </tbody>
		</table>
		
{% else %}
	<div class="lead"> Cart is empty</div>
{% endif %}


{% endblock %}

src/carts/templates/carts/order_detail.html
{% extends "base.html" %}


{% block content %}
<div class='container'>
<ul class="list-group list-group-flush">
  <li class="list-group-item">Cart Items: {% for product in object.cart.products.all %}{{ product }}{% if not forloop.last %}, {% endif %}{% endfor %}</li>
  <li class="list-group-item">Shipping Address: {{ object.shipping_address }}</li>
  <li class="list-group-item">Shipping Total: {{ object.shipping_total }}</li>
  <li class="list-group-item">Order Status {{object.status}}</li>
  <li class="list-group-item">Order Total: {{ object.total }}</li>
</ul>
{% if object.status == 'created' %}<br>
<a class='btn btn-success' href="{% url 'carts:OrderDelete' object.id %}" class="card-link">Delete</a>
<a class='btn btn-info' href="{% url 'carts:home' %}" class="card-link">Edit</a>{%endif%}</div>
{% endblock %}

src/carts/templates/carts/pay.html
{% extends 'base.html'%}
{% block content%}
<!DOCTYPE html>

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
</head>

<body>

 <strong class="text-danger">This is Not Commerical site Don't Pay anyThing ,This is Educational site we are not responsible for any money Transactions</strong>

  <script
    src="https://www.paypal.com/sdk/js?client-id=AcPOcNCbqa2vzYmWe84VFwONMRHvrx7HKfKsWPQZLsdk8JfGW6CTz58cXEjS9xDAILeS-eE1oaoVTAph">
  </script>
   <div id="paypal-button-container"></div>
  <script>
  paypal.Buttons({
    createOrder: function(data, actions) {
      return actions.order.create({
        purchase_units: [{
          amount: {
            value: '0.01'
          }
        }]
      });
    },
    onApprove: function(data, actions) {
      return actions.order.capture().then(function(details) {
        alert('Transaction completed by ' + details.payer.name.given_name);
        // Call your server to save the transaction
        return fetch('/paypal-transaction-complete', {
          method: 'post',
          headers: {
            'content-type': 'application/json'
          },
          body: JSON.stringify({
            orderID: data.orderID
          })
        });
      });
    }
  }).render('#paypal-button-container');
</script>


</body>
{% endblock %}
 