src/carts/urls.py
from django.urls import path, include

from .views import (
				cart_home,
				cart_add,
				checkout_home,
				checkout_done_view,
				# cart_remove,
				OrderDetail,
				OrderDelete,
				pay,
				)
app_name= "carts"
urlpatterns = [
	path('', cart_home, name="home"),
	path('update', cart_add, name="update"),
	# path('remove', cart_remove, name="remove"),
	path('checkout', checkout_home, name="checkout"),
	path('checkout/done', checkout_done_view, name="checkout_done"),
	path('order/<pk>', OrderDetail.as_view(), name="OrderDetail"),
	path('order/<int:pk>/delete', OrderDelete.as_view(), name="OrderDelete"),
	# path('paypal/', include('paypal.standard.ipn.urls')),
	path('pay/',pay,name='pay'),
	# path('guest_register', guest_register_view, name="guest_register"),
	# path('delete/<id>', removeproduct, name="remove"),
	]

src/ecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.contrib import admin
from django.views.generic.base import TemplateView
from .views import home_page, about_page, contact_page
from django.contrib.auth.views import LogoutView
from accounts.views import login_page, register_page#, guest_register_view
from addresses.views import checkout_address_create_view
urlpatterns = [
	path('', home_page, name="home"),
	path('about/', about_page, name="about"),
	path('contact/', contact_page, name="contact"),
	#path(r'contact/view', contact_page),
	path('checkout/address/create', checkout_address_create_view, name="ckeckout_address_create"),
	path('login', login_page, name="login"),
	# path('register_guest', guest_register_view, name="guest_register"),
	path('logout/', LogoutView.as_view(), name="logout"),
	path('register', register_page , name="register"),
	path('bootstrap',TemplateView.as_view(template_name="bootstrap/example.html")),
	path('products/', include("products.urls")),
	path('search/', include("search.urls")),
	path('cart/', include("carts.urls")),
	# path('cart/', cart_home, name="cart"),
	path('admin/', admin.site.urls),
	path('ratings/', include('star_ratings.urls', namespace='ratings')),
    ]
if settings.DEBUG:
	urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/products/urls.py
from django.urls import path,include

from products.views import (
				ProductListView,
				ProductDetailslugView,
				ProductMenView,
				ProductWomenView
				)
app_name= "products"
urlpatterns = [
	path('', ProductListView.as_view(), name="list"),
	path('<slug>', ProductDetailslugView.as_view(), name="detail"),
	path('men/',ProductMenView.as_view(),name='men'),
	path('women/',ProductWomenView.as_view(),name='women')
	#url(r'^products/(?P<pk>\d+)/$', ProductDetailView.as_view()),
	

	#url(r'^products-fbv/(?P<pk>\d+)/$', product_detail_view),
	#url(r'^featured/$', ProductFeaturedListView.as_view()),
	#url(r'^featured/(?P<pk>\d+)/$', ProductFeaturedDetailView.as_view()),

	
	#url(r'^products-fbv/$', product_list_view),
	
]

src/products/models.py
from django.db import models
import random
import os
from django.urls import reverse
from django.db.models.signals import pre_save, post_save
from ecommerce.utils import unique_slug_generator
from django.contrib.auth.models import User

class ProductQueryset(models.query.QuerySet):
	def active(self):
		return self.filter(active=True)
	def get_by_id(self, id):
		qs = self.filter(id=id)
		if qs.count()== 1:
			return qs.first()
		else:
			return None	
	def featured(self):
		return self.filter(featured=True)
	def men(self):
		return self.filter(gender='men')
	# def all(self):
	# 	return self.filter(active=True)
# class  ProductManager(models.Manager):
# 	def get_queryset(self):
# 		return ProductQueryset(self.model, using=self._db)
# 	def featured(self):
# 		return self.get_queryset().filter(featured=True)
# 	def all(self):
# 		return self.get_queryset().active()
	
# 	def search(self, query):
# 		return self.get_queryset().active().search(query)

GENDER_CHOISES=(

		('men', "Men"),
		('women', "Women"),)
class Product(models.Model):
	title         = models.CharField(max_length=120)
	slug          = models.SlugField(blank=True, unique=True)
	description   = models.TextField()
	price         = models.DecimalField(decimal_places=2, max_digits=20, default=39.99)
	image         = models.ImageField(upload_to='products', null=True, blank=False)
	featured      = models.BooleanField(default=False)
	active        = models.BooleanField(default=True)
	gender 		  = models.CharField(max_length=120,default="" ,choices=GENDER_CHOISES)
	timestamp     = models.DateTimeField(auto_now_add=True)
	
	objects = ProductQueryset.as_manager()


	def get_absolute_url(self):
		#return "/products/{slug}/".format(slug=self.slug)
		return reverse("products:detail", kwargs={"slug":self.slug})

	def __str__(self):
		"""show product name in admin page"""
		return self.title


	def product_pre_save_receiver(sender, instance, *args, **kwargs):
		if not instance.slug:
			instance.slug = unique_slug_generator(instance)
		pre_save.connect(Product_pre_save_receiver, sender=Product)

src/products/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView
# Create your views here.
from .models import Product
from django.core.paginator import Paginator

from django.http import Http404 
from carts.models import Cart
class ProductFeaturedListView(ListView):
	
	template_name = "products/list.html"
	def get_queryset(self, *args, **kwargs):
		request = self.request
		return Product.objects.featured()

class ProductMenView(ListView):
	queryset = Product.objects.filter(gender='men')
	template_name = "products/snippets/men.html"
class ProductWomenView(ListView):
	queryset = Product.objects.filter(gender='women')
	template_name = "products/snippets/women.html"	
	 # Show 25 contacts per page

	# def get_queryset(self, *args, **kwargs):
	# 	request = self.request
	# 	return Product.objects.featured()
class ProductListView(ListView):
	queryset = Product.objects.all()
	template_name = "products/list.html"
	paginate_by=6
	# # def get_context_data(self, *args, **kwargs):
	# 	context = super(ProductListView,self).get_context_data(*args, **kwargs)
	# 	print (context)
	# 	return context

# def product_list_view(request):
# 	queryset = Product.objects.all()
# 	context = {
# 		'object_list': queryset
# 	}
# 	return render(request, 'products/list.html', context)

class ProductDetailslugView(DetailView):
	queryset = Product.objects.all()

	template_name = "products/detail.html"
	def get_context_data(self, *args, **kwargs):
		context=super(ProductDetailslugView, self).get_context_data(*args, **kwargs)
		cart_obj, new_obj = Cart.objects.new_or_get(self.request)
		context['cart']= cart_obj
		return context
class ProductDetailView(DetailView):
	
	#queryset = Product.objects.all()#make aqueryset
	template_name = "products/detail.html"

	# def get_context_data(self, *args, **kwargs):
	# 	context = super(ProductDetailView, self).get_context_data(*args, **kwargs)
	# 	print (context)
	# 	return context
	def get_object(self, *args, **kwargs):
		request = self.request
		pk = self.kwargs.get('pk')
		instance = Product.objects.get_by_id(pk)
		if instance is None:
			raise Http404("Product Not Here!")
		return instance
def product_detail_view(request, pk=None):
	#instance  = Product.objects.get(pk=pk)#id
	#instance = get_object_or_404(Product, pk=pk)
	# try:
	# 	instance=Product.objects.get(id=pk)
	# except Product.DoesNotExist:
	# 	print("No products here")
	# 	raise Http404("product not exist")
	# except:
	# 	print("huh?")
	instance = Product.objects.get_by_id(pk)
	if instance is None:
		raise Http404("Product Not Here!")
	#print (instance)
	# qs = Product.objects.filter(id=pk)
	# if qs.exists() and qs.count()==1:#count() returns the number of occurrences of a substring in the given string
	#determine the number of records in the set
	# 	instance = qs.first() #Return the first true value of an iterable
	# else:
	# 	raise Http404("Product Not Here!")
	context = {
		'object': instance
	}
	return render(request, 'products/detail.html', context)

src/products/templates/products/snippets/card.html
<div class="card" style="width: 18rem;">
	{% if product.image %}
	<a href="{{ product.get_absolute_url}}">
  	<img src="{{ product.image.url}}" class="card-img-top" alt="{{ product.title}} logo"  >
  	</a>
  {% endif %}
  <div class="card-body">
    <h5 class="card-title">{{ product.title }}</h5>
    <p class="card-text">{{ product.description|truncatewords:12 }}.</p>
    <div>{{product.price}}&#163;</div>
    <a href="{{ product.get_absolute_url}}" class="btn btn-primary">View</a> <!-- same as next -->
    <div class="btn btn-success btn-sm">
    {% include "products/update_cart.html"  %}
  
</div>
  </div>
</div>

src/products/templates/products/snippets/gender.html
 <div class="row " style="text-align: center;width: 100%;display: inline-block;">
 	<a  role="button"type="button" href="{% url 'products:list' %}" class="btn btn-secondary">
   All</a> &nbsp;
  	 	<a type="button" href="{% url 'products:men' %}" class="btn btn-light">
   Men</a>&nbsp;
 
 <a type="button" href="{% url 'products:women' %}"class="btn btn-light"> Women
 </a>
</div><br><hr>

src/products/templates/products/snippets/men.html
{%extends 'base.html'%}
{%block content%}
{% include 'products/snippets/gender.html'%}
<h1>Men Collection</h1><hr>
		<div class="row">

	{% for product in object_list %}
	<div class="col">
		<!-- {{ forloop.counter }} -->
		{% include 'products/snippets/card.html'%}
		
		{% if forloop.counter|divisibleby:3 %}
	  	 </div></div>
	  	 <div class="row"><div class="col-12"><hr></div>
	   {%  else %}
           </div>
	   {% endif %}
	   
	
	{% endfor %}

</div>

{% endblock %}

src/products/templates/products/snippets/women.html
{%extends 'base.html'%}
{%block content%}
{% include 'products/snippets/gender.html'%}
<h1>Women Collection</h1><hr>
<div class="row">

	{% for product in object_list %}
	<div class="col">
		<!-- {{ forloop.counter }} -->
		{% include 'products/snippets/card.html'%}
		
		{% if forloop.counter|divisibleby:3 %}
	  	 </div></div>
	  	 <div class="row"><div class="col-12"><hr></div>
	   {%  else %}
           </div>
	   {% endif %}
	   
	
	{% endfor %}

</div>

{% endblock %}